spring.application.name=employee-manangement
# =============================================
# PostgreSQL DataSource Configuration
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/employee-management-system
spring.datasource.username=nguyen.duc.huyb
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
# =============================================
# Spring Data JPA / Hibernate Configuration
# =============================================
# update: tự động cập nhật schema theo entity (dùng cho dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
